extends:
  - "airbnb-typescript"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
parser: "@typescript-eslint/parser"
parserOptions:
  project:
    - "tsconfig.json"
plugins:
  - "@typescript-eslint"
root: true
rules:
  "@typescript-eslint/no-explicit-any": "off"
  "@typescript-eslint/no-floating-promises":
    - error
    - ignoreIIFE: true
      ignoreVoid: true
  "@typescript-eslint/no-inferrable-types": "off"
  "@typescript-eslint/no-unused-vars":
    - warn
    - argsIgnorePattern: _
      varsIgnorePattern: _
  arrow-body-style: "off"
  func-names: "off"
  import/prefer-default-export: "off"
  no-console: "off"
  no-else-return: "off"
  object-shorthand: "off"
  react/react-in-jsx-scope: "off"
